MANIFEST.in: add missing files to Pypi SDIST
otherwise it could not be compiled, hope this works, can't test it:

```
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 0.58, 0.82, 0.62
 * Package:    dev-python/pycketcasts-1.0.0
 * Repository: HomeAssistantRepository
 * Maintainer: b@edevau.net
 * Upstream:   n8gr8gbln@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_8 test userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking pycketcasts-1.0.0.tar.gz to /var/tmp/portage/dev-python/pycketcasts-1.0.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/pycketcasts-1.0.0/work
>>> Preparing source in /var/tmp/portage/dev-python/pycketcasts-1.0.0/work/pycketcasts-1.0.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/pycketcasts-1.0.0/work/pycketcasts-1.0.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/pycketcasts-1.0.0/work/pycketcasts-1.0.0 ...
 * python3_8: running distutils-r1_run_phase distutils-r1_python_compile
python3.8 setup.py build -j 10
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    with open("requirements.txt", 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
 * ERROR: dev-python/pycketcasts-1.0.0::HomeAssistantRepository failed (compile phase):
 *   (no error message)
```